/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.danielcastellani.gerenciadordetarefas.gui;

import br.danielcastellani.gerenciadordetarefas.contexto.Contexto;
import br.danielcastellani.gerenciadordetarefas.controle.TelaTarefaListagemControlador;
import br.danielcastellani.gerenciadordetarefas.modelo.Projeto;

/**
 *
 * @author Daniel
 */
public class TelaTarefaListagem extends javax.swing.JInternalFrame {

    private TelaTarefaListagemControlador controlador;
    private Projeto projeto;

    /**
     * Creates new form TelaProjetoListagem
     */
    public TelaTarefaListagem(Projeto projeto) {
        this.projeto = projeto;
        initComponents();
        this.setTitle("Ver Projeto: " + projeto.getNome());
        controlador = new TelaTarefaListagemControlador(this);
       Contexto.getInstance().put(controlador.getClass().getCanonicalName(), controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListagem = new javax.swing.JPanel();

        setClosable(true);
        setTitle(projeto.getNome());

        panelListagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelListagem.setAutoscrolls(true);
        panelListagem.setMinimumSize(new java.awt.Dimension(200, 0));

        javax.swing.GroupLayout panelListagemLayout = new javax.swing.GroupLayout(panelListagem);
        panelListagem.setLayout(panelListagemLayout);
        panelListagemLayout.setHorizontalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        panelListagemLayout.setVerticalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelListagem;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelListagem
     */
    public javax.swing.JPanel getPanelListagem() {
        return panelListagem;
    }

    /**
     * @param panelListagem the panelListagem to set
     */
    public void setPanelListagem(javax.swing.JPanel panelListagem) {
        this.panelListagem = panelListagem;
    }
    
}
